package com.bcp.modelo;

public class app_esp_informacion_general {
	
	public final int getID_APLICACION_ESPECIALIZADA() {
		return ID_APLICACION_ESPECIALIZADA;
	}
	public final void setID_APLICACION_ESPECIALIZADA(int iD_APLICACION_ESPECIALIZADA) {
		ID_APLICACION_ESPECIALIZADA = iD_APLICACION_ESPECIALIZADA;
	}
	public final String getNOMBRE_APLICACION_NOIT() {
		return NOMBRE_APLICACION_NOIT;
	}
	public final void setNOMBRE_APLICACION_NOIT(String nOMBRE_APLICACION_NOIT) {
		NOMBRE_APLICACION_NOIT = nOMBRE_APLICACION_NOIT;
	}
	public final String getDESCRICION_APLICACION() {
		return DESCRICION_APLICACION;
	}
	public final void setDESCRICION_APLICACION(String dESCRICION_APLICACION) {
		DESCRICION_APLICACION = dESCRICION_APLICACION;
	}
	public final String getFUNCIONALIDADES_APLICACION() {
		return FUNCIONALIDADES_APLICACION;
	}
	public final void setFUNCIONALIDADES_APLICACION(
			String fUNCIONALIDADES_APLICACION) {
		FUNCIONALIDADES_APLICACION = fUNCIONALIDADES_APLICACION;
	}
	public final int getID_ESTADO_APLICACION() {
		return ID_ESTADO_APLICACION;
	}
	public final void setID_ESTADO_APLICACION(int iD_ESTADO_APLICACION) {
		ID_ESTADO_APLICACION = iD_ESTADO_APLICACION;
	}
	public final int getID_TIPO_OPERACION_PROCESO() {
		return ID_TIPO_OPERACION_PROCESO;
	}
	public final void setID_TIPO_OPERACION_PROCESO(int iD_TIPO_OPERACION_PROCESO) {
		ID_TIPO_OPERACION_PROCESO = iD_TIPO_OPERACION_PROCESO;
	}
	public final int getID_FRECUENCIA_OPERACIONES() {
		return ID_FRECUENCIA_OPERACIONES;
	}
	public final void setID_FRECUENCIA_OPERACIONES(int iD_FRECUENCIA_OPERACIONES) {
		ID_FRECUENCIA_OPERACIONES = iD_FRECUENCIA_OPERACIONES;
	}
	public final int getID_CANTIDAD_OPERACIONES() {
		return ID_CANTIDAD_OPERACIONES;
	}
	public final void setID_CANTIDAD_OPERACIONES(int iD_CANTIDAD_OPERACIONES) {
		ID_CANTIDAD_OPERACIONES = iD_CANTIDAD_OPERACIONES;
	}
	public final String getFECHA_CREACION_APLICACION() {
		return FECHA_CREACION_APLICACION;
	}
	public final void setFECHA_CREACION_APLICACION(String fECHA_CREACION_APLICACION) {
		FECHA_CREACION_APLICACION = fECHA_CREACION_APLICACION;
	}
	public final int getID_MOTIVO_CREACION_APLICACION() {
		return ID_MOTIVO_CREACION_APLICACION;
	}
	public final void setID_MOTIVO_CREACION_APLICACION(
			int iD_MOTIVO_CREACION_APLICACION) {
		ID_MOTIVO_CREACION_APLICACION = iD_MOTIVO_CREACION_APLICACION;
	}
	public final String getMOTIVO_CREACION_APLICACION_OTROS() {
		return MOTIVO_CREACION_APLICACION_OTROS;
	}
	public final void setMOTIVO_CREACION_APLICACION_OTROS(
			String mOTIVO_CREACION_APLICACION_OTROS) {
		MOTIVO_CREACION_APLICACION_OTROS = mOTIVO_CREACION_APLICACION_OTROS;
	}
	public final int getNRO_FUNCIONALIDADES_TRANSACCIONES() {
		return NRO_FUNCIONALIDADES_TRANSACCIONES;
	}
	public final void setNRO_FUNCIONALIDADES_TRANSACCIONES(
			int nRO_FUNCIONALIDADES_TRANSACCIONES) {
		NRO_FUNCIONALIDADES_TRANSACCIONES = nRO_FUNCIONALIDADES_TRANSACCIONES;
	}
	public final int getNRO_REPORTES() {
		return NRO_REPORTES;
	}
	public final void setNRO_REPORTES(int nRO_REPORTES) {
		NRO_REPORTES = nRO_REPORTES;
	}
	public final int getNRO_CONSULTAS() {
		return NRO_CONSULTAS;
	}
	public final void setNRO_CONSULTAS(int nRO_CONSULTAS) {
		NRO_CONSULTAS = nRO_CONSULTAS;
	}
	public final int getNRO_ENTIDADES_EXTERNAS() {
		return NRO_ENTIDADES_EXTERNAS;
	}
	public final void setNRO_ENTIDADES_EXTERNAS(int nRO_ENTIDADES_EXTERNAS) {
		NRO_ENTIDADES_EXTERNAS = nRO_ENTIDADES_EXTERNAS;
	}
	public final int getNRO_ENTIDADES_INTERNAS() {
		return NRO_ENTIDADES_INTERNAS;
	}
	public final void setNRO_ENTIDADES_INTERNAS(int nRO_ENTIDADES_INTERNAS) {
		NRO_ENTIDADES_INTERNAS = nRO_ENTIDADES_INTERNAS;
	}
	public final String getOBSERVACIONES_GENERALES() {
		return OBSERVACIONES_GENERALES;
	}
	public final void setOBSERVACIONES_GENERALES(String oBSERVACIONES_GENERALES) {
		OBSERVACIONES_GENERALES = oBSERVACIONES_GENERALES;
	}
	
	private int ID_APLICACION_ESPECIALIZADA;
	private String NOMBRE_APLICACION_NOIT;
	private String DESCRICION_APLICACION;
	private String FUNCIONALIDADES_APLICACION;
	private int ID_ESTADO_APLICACION;
	private int ID_TIPO_OPERACION_PROCESO;
	private int ID_FRECUENCIA_OPERACIONES;
	private int ID_CANTIDAD_OPERACIONES;
	private String FECHA_CREACION_APLICACION;
	private int ID_MOTIVO_CREACION_APLICACION;
	private String MOTIVO_CREACION_APLICACION_OTROS;
	private int NRO_FUNCIONALIDADES_TRANSACCIONES;
	private int NRO_REPORTES;
	private int NRO_CONSULTAS;
	private int NRO_ENTIDADES_EXTERNAS;
	private int NRO_ENTIDADES_INTERNAS;
	private String OBSERVACIONES_GENERALES;

}
